# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171220_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nick_name',
            new_name='nickName',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avataUrl',
            field=models.CharField(default='', max_length=200, verbose_name='\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='\u57ce\u5e02'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(default='', max_length=50, verbose_name='\u7701\u4efd'),
        ),
    ]
