# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171220_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='open_id',
            new_name='openId',
        ),
    ]
