# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171220_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avataUrl',
            new_name='avatarUrl',
        ),
    ]
