# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-24 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20171224_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attention',
            old_name='user',
            new_name='userProfile',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='userProfile',
        ),
    ]
