# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsinfo', '0006_auto_20171225_1106'),
        ('operations', '0003_auto_20171224_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='CarsVideo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carsinfo.CarsVideo'),
        ),
    ]
