# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_favorite_carsvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='CarsVideo',
            new_name='carsVideo',
        ),
    ]
