# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsinfo', '0006_auto_20171225_1106'),
        ('operations', '0006_auto_20171225_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='carsVideo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carsinfo.CarsVideo', verbose_name='\u6240\u5c5e\u89c6\u9891'),
        ),
    ]
