# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-19 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u89c6\u9891\u540d')),
                ('desc', models.CharField(max_length=300, verbose_name='\u89c6\u9891\u63cf\u8ff0')),
                ('url', models.URLField(max_length=150, verbose_name='\u89c6\u9891\u94fe\u63a5')),
                ('duration', models.IntegerField(default=0, verbose_name='\u65f6\u957f')),
                ('play_nums', models.IntegerField(default=0, verbose_name='\u64ad\u653e\u6570')),
                ('cover', models.ImageField(upload_to='video/%Y/%m', verbose_name='\u5c01\u9762')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('cars_org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CarOrg', verbose_name='\u6240\u5c5e\u673a\u6784')),
            ],
            options={
                'verbose_name': '\u89c6\u9891\u8d44\u6e90',
                'verbose_name_plural': '\u89c6\u9891\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6807\u7b7e\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
    ]
