# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-19 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsvideo',
            old_name='cars_org_id',
            new_name='cars_org',
        ),
    ]
