# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-19 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsinfo', '0002_auto_20171219_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='carsVideo',
            field=models.ManyToManyField(to='carsinfo.CarsVideo', verbose_name='\u89c6\u9891\u8d44\u6e90'),
        ),
    ]
