# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-20 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsinfo', '0003_tags_carsvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': '\u6807\u7b7e', 'verbose_name_plural': '\u6807\u7b7e'},
        ),
        migrations.RenameField(
            model_name='carsvideo',
            old_name='cars_org',
            new_name='carsOrg',
        ),
    ]
