# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsinfo', '0004_auto_20171220_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='carsVideo',
        ),
        migrations.AddField(
            model_name='carsvideo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='carsinfo.Tags', verbose_name='\u89c6\u9891\u8d44\u6e90'),
        ),
    ]
