# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsinfo', '0005_auto_20171221_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carsvideo',
            options={'ordering': ['-add_time'], 'verbose_name': '\u89c6\u9891\u8d44\u6e90', 'verbose_name_plural': '\u89c6\u9891\u8d44\u6e90'},
        ),
        migrations.AlterField(
            model_name='carsvideo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='carsinfo.Tags', verbose_name='\u6807\u7b7e'),
        ),
    ]
